// Handling possibility of failure

fn main(){

}